"""Re-export shim: map rendering lives in app.rendering.map_image."""
from app.rendering.map_image import (
    CELL_PX,
    CLAIM_BORDER,
    HIGHLIGHT_BORDER,
    ICON_PX,
    LABEL_LEFT_PX,
    LABEL_TOP_PX,
    MapImageCache,
    MapPhoto,
    PAD_PX,
    RENDER_REV,
    TILE_COLORS,
    TILE_ICONS,
    build_map_caption,
    building_visible_on_map,
    map_fingerprint,
    render_map_image,
    require_map_font,
)

__all__ = [
    "CELL_PX",
    "CLAIM_BORDER",
    "HIGHLIGHT_BORDER",
    "ICON_PX",
    "LABEL_LEFT_PX",
    "LABEL_TOP_PX",
    "MapImageCache",
    "MapPhoto",
    "PAD_PX",
    "RENDER_REV",
    "TILE_COLORS",
    "TILE_ICONS",
    "build_map_caption",
    "building_visible_on_map",
    "map_fingerprint",
    "render_map_image",
    "require_map_font",
]
